debugSource('readData.R')
par(mfrow = c(1,1))
#Sys.setlocale(category = "LC_ALL", locale = "english")
consumption <- readData()
with(consumption, plot(Date, Sub_metering_1, type = 'l',xlab = 'Day',col = 'black', ylab = 'Energy Sub metering'))
with(consumption, lines(Date, Sub_metering_2, type = 'l',xlab = 'Day', col = 'red'))
with(consumption, lines(Date, Sub_metering_3, type = 'l',xlab = 'Day', col = 'blue'))
legend('topright', c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=c('black','red','blue'), lty = c(1,1,1))
dev.copy(png,'plot3.png')
dev.off()